import type { ApiInfo } from "./fal";

export const RUNWARE_ENDPOINTS: ApiInfo[] = [
  {
    provider: "runware",
    endpointId: "vidu:q1@image",
    label: "Vidu Q1",
    description: "High-quality image generation from Vidu",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "bytedance:5@0",
    label: "Seedream 4.0",
    description: "Advanced image generation with creative control",
    popularity: 5,
    category: "image",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "google:4@1",
    label: "Gemini Flash Image 2.5",
    description: "Fast image generation from Google",
    popularity: 5,
    category: "image",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "runware:108@20",
    label: "Qwen-Image-Edit",
    description: "Advanced image editing capabilities",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "runware:108@21",
    label: "Qwen-Image-Edit Lightning (8 steps)",
    description: "Fast image editing with 8-step inference",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "runware:108@22",
    label: "Qwen-Image-Edit-Plus",
    description: "Enhanced image editing with advanced capabilities",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "klingai:4@10",
    label: "Kolors 2.1",
    description: "Advanced color-aware image generation",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "klingai:5@10",
    label: "Kolors 2.0",
    description: "Color-focused image generation model",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:109@1",
    label: "FLUX.1 [dev] SRPO",
    description: "FLUX development model with SRPO optimization",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:108@1",
    label: "Qwen-Image",
    description: "Multimodal image generation from Qwen",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:108@5",
    label: "Qwen-Image-Lightning (4 steps)",
    description: "Ultra-fast image generation in 4 steps",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:108@6",
    label: "Qwen-Image-Lightning (8 steps V1.0)",
    description: "Fast image generation in 8 steps",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:108@7",
    label: "Qwen-Image-Lightning (8 steps V1.1)",
    description: "Improved 8-step image generation",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:107@1",
    label: "FLUX.1 Krea [dev]",
    description: "FLUX model optimized for creative workflows",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "bytedance:4@1",
    label: "SeedEdit 3.0",
    description: "Advanced image editing from ByteDance",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "bytedance:3@1",
    label: "Seedream 3.0",
    description: "High-quality image generation with realism",
    popularity: 5,
    category: "image",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@1",
    label: "Ideogram 3.0",
    description: "Text-to-image with superior text rendering",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@2",
    label: "Ideogram 3.0 Remix",
    description: "Image remixing with style transfer",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@3",
    label: "Ideogram 3.0 Edit",
    description: "Precise image editing capabilities",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@4",
    label: "Ideogram 3.0 Reframe",
    description: "Image reframing and composition",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@5",
    label: "Ideogram 3.0 Replace Background",
    description: "Background replacement for images",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "bria:10@1",
    label: "Bria 3.2",
    description: "Advanced image generation from Bria",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "bria:11@1",
    label: "Bria Replace Background",
    description: "Professional background replacement",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "runware:160@1",
    label: "Flex.1-alpha",
    description: "Flexible image generation model",
    popularity: 3,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:160@2",
    label: "Flex.1-alpha Redux",
    description: "Enhanced flexible image generation",
    popularity: 3,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "google:2@1",
    label: "Imagen 4 Preview",
    description: "Preview version of Google Imagen 4",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "google:2@2",
    label: "Imagen 4.0 Ultra",
    description: "Highest quality Imagen 4 model",
    popularity: 5,
    category: "image",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "google:2@3",
    label: "Imagen 4.0 Preview Fast",
    description: "Fast preview image generation from Google",
    popularity: 5,
    category: "image",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "openai:1@1",
    label: "GPT Image 1",
    description: "Image generation from OpenAI",
    popularity: 4,
    category: "image",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "runware:106@1",
    label: "FLUX.1 Kontext [dev]",
    description: "FLUX development with context awareness",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "bfl:3@1",
    label: "FLUX.1 Kontext [pro]",
    description: "Professional FLUX with context",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "bfl:4@1",
    label: "FLUX.1 Kontext [max]",
    description: "Maximum quality FLUX with context",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "bfl:2@1",
    label: "FLUX.1.1 [pro]",
    description: "Professional FLUX version 1.1",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "bfl:2@2",
    label: "FLUX.1.1 [pro] Ultra",
    description: "Ultra high-quality FLUX 1.1 Pro",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:97@1",
    label: "HiDream-I1 v1",
    description: "High-quality dream-like image generation v1",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:97@2",
    label: "HiDream-I1 v2",
    description: "High-quality dream-like image generation v2",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:97@3",
    label: "HiDream-I1 v3",
    description: "High-quality dream-like image generation v3",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "rundiffusion:130@100",
    label: "Juggernaut Pro Flux by RunDiffusion",
    description: "Professional quality Flux model",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "rundiffusion:110@101",
    label: "Juggernaut Lightning Flux by RunDiffusion",
    description: "Ultra-fast Flux generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:133005@782002",
    label: "Juggernaut XL",
    description: "Versatile realistic image generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:4201@130072",
    label: "Realistic Vision",
    description: "Photorealistic image generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:25694@143906",
    label: "DreamShaper",
    description: "Creative and artistic generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:7240@119057",
    label: "MeinaMix",
    description: "Anime-style image generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:81458@132760",
    label: "Epic Realism",
    description: "Ultra-realistic image generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "sourceful:1@0",
    label: "Sourceful v1.0",
    description: "Sourceful image generation model v1.0",
    popularity: 3,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "sourceful:1@1",
    label: "Sourceful v1.1",
    description: "Sourceful image generation model v1.1",
    popularity: 3,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "sourceful:1@2",
    label: "Sourceful v1.2",
    description: "Sourceful image generation model v1.2",
    popularity: 3,
    category: "image",
  },

  // ByteDance Video Models
  {
    provider: "runware",
    endpointId: "bytedance:2@2",
    label: "Seedance 1.0 Pro Fast",
    description: "Fast variant of Seedance 1.0 Pro for high-speed video generation",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "bytedance:2@1",
    label: "Seedance 1.0 Pro",
    description: "High-quality video generation with advanced features",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "bytedance:1@1",
    label: "Seedance 1.0 Lite",
    description: "Lightweight video generation model",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "bytedance:5@2",
    label: "OmniHuman-1.5",
    description: "Enhanced human animation from image and audio",
    popularity: 5,
    category: "video",
    inputAsset: ["image", "audio"],
  },
  {
    provider: "runware",
    endpointId: "bytedance:5@1",
    label: "OmniHuman-1",
    description: "Human animation from image and audio",
    popularity: 4,
    category: "video",
    inputAsset: ["image", "audio"],
  },

  // Lightricks Video Models
  {
    provider: "runware",
    endpointId: "lightricks:2@0",
    label: "LTX-2 Pro",
    description: "High-quality video generation from Lightricks",
    popularity: 5,
    category: "video",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "lightricks:2@1",
    label: "LTX-2 Fast",
    description: "Fast video generation from Lightricks",
    popularity: 5,
    category: "video",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },

  // KlingAI Video Models
  {
    provider: "runware",
    endpointId: "klingai:6@0",
    label: "KlingAI 2.5 Turbo Standard",
    description: "Image-to-video with KlingAI 2.5 Turbo Standard",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "klingai:6@1",
    label: "KlingAI 2.5 Turbo Pro",
    description: "Text-to-video and image-to-video with KlingAI 2.5 Turbo Pro",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "klingai:5@3",
    label: "KlingAI 2.1 Master",
    description: "Master quality video generation with text and image support",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "klingai:5@2",
    label: "KlingAI 2.1 Pro",
    description: "Pro quality image-to-video generation",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "klingai:5@1",
    label: "KlingAI 2.1 Standard",
    description: "Standard quality image-to-video generation",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "klingai:4@3",
    label: "KlingAI 2.0 Master",
    description: "Master quality video generation with text and image support",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "klingai:3@2",
    label: "KlingAI 1.6 Pro",
    description: "Pro quality image-to-video generation",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "klingai:3@1",
    label: "KlingAI 1.6 Standard",
    description: "Standard quality video generation with text and image support",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },

  // MiniMax Video Models
  {
    provider: "runware",
    endpointId: "minimax:4@1",
    label: "MiniMax Hailuo 2.3",
    description: "Latest MiniMax Hailuo video generation model",
    popularity: 5,
    category: "video",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "minimax:4@2",
    label: "MiniMax Hailuo 2.3 Fast",
    description: "Fast variant of MiniMax Hailuo 2.3 for high-speed generation",
    popularity: 5,
    category: "video",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "minimax:3@1",
    label: "MiniMax 02 Hailuo",
    description: "MiniMax Hailuo 02 text-to-video model",
    popularity: 5,
    category: "video",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "minimax:2@1",
    label: "MiniMax 01 Director",
    description: "MiniMax Hailuo 01 Director with text and image support",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },

  // Vidu Video Models
  {
    provider: "runware",
    endpointId: "vidu:3@2",
    label: "Vidu Q2 Turbo",
    description: "High-speed Vidu Q2 video generation with reference support",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "vidu:3@1",
    label: "Vidu Q2 Pro",
    description: "Professional Vidu Q2 video generation with enhanced quality",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "vidu:1@1",
    label: "Vidu Q1",
    description: "Vidu Q1 video generation with text and image support",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },

  // Google Veo Video Models
  {
    provider: "runware",
    endpointId: "google:3@3",
    label: "Google Veo 3.1 Fast",
    description:
      "Optimized variant of Veo 3.1 for high-speed generation with cinematic quality",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "google:3@2",
    label: "Google Veo 3.1",
    description:
      "Google's newest Veo model for cinematic video generation with natural sound",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "google:3@1",
    label: "Google Veo 3 Fast",
    description:
      "Faster and more cost-effective variant of Veo 3, optimized for speed and affordability while maintaining native audio generation capabilities",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "google:3@0",
    label: "Google Veo 3",
    description: "Google Veo 3 video generation with text and image support",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },

  // OpenAI Sora Video Models
  {
    provider: "runware",
    endpointId: "openai:3@2",
    label: "Sora 2 Pro",
    description: "OpenAI's Sora 2 Pro with enhanced quality and resolution",
    cost: "~$0.5/video",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "openai:3@1",
    label: "Sora 2",
    description: "OpenAI's Sora 2 video generation model",
    cost: "$0.4/video",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },

  // PixVerse Video Models
  {
    provider: "runware",
    endpointId: "pixverse:1@5",
    label: "PixVerse v5",
    description: "Latest PixVerse video generation with text and image support",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "pixverse:1@3",
    label: "PixVerse v4.5",
    description: "PixVerse v4.5 video generation with text and image support",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
    initialInput: {
      positivePrompt: "",
      seedImage: "",
    },
    inputMap: {
      prompt: "positivePrompt",
      image: "seedImage",
      image_url: "seedImage",
      seedImage: "seedImage",
    },
  },
  {
    provider: "runware",
    endpointId: "pixverse:lipsync@1",
    label: "PixVerse LipSync",
    description: "Lip sync for video avatars",
    popularity: 4,
    category: "video",
    inputAsset: ["video", "audio"],
  },

  // Runware Video Models
  {
    provider: "runware",
    endpointId: "runware:201@1",
    label: "Wan2.5-Preview",
    description: "Preview of Runware Wan 2.5 video model",
    popularity: 5,
    category: "video",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "runware:200@8",
    label: "Wan2.2 A14B Turbo",
    description: "Turbo variant of Runware Wan 2.2 A14B for high-speed generation",
    popularity: 5,
    category: "video",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "runware:200@6",
    label: "Wan2.2 A14B",
    description: "Runware Wan 2.2 A14B video generation model",
    popularity: 5,
    category: "video",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },
  {
    provider: "runware",
    endpointId: "runware:190@1",
    label: "Ovi",
    description: "Runware Ovi video generation model",
    popularity: 5,
    category: "video",
    initialInput: {
      positivePrompt: "",
    },
    inputMap: {
      prompt: "positivePrompt",
    },
  },

  {
    provider: "runware",
    endpointId: "elevenlabs:1@1",
    label: "ElevenLabs Music v1",
    description: "Music generation from ElevenLabs",
    popularity: 4,
    category: "music",
  },
];
