import type { ApiInfo } from "./fal";

export const RUNWARE_ENDPOINTS: ApiInfo[] = [
  {
    provider: "runware",
    endpointId: "vidu:q1@image",
    label: "Vidu Q1",
    description: "High-quality image generation from Vidu",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "bytedance:5@0",
    label: "Seedream 4.0",
    description: "Advanced image generation with creative control",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
    hasNegativePrompt: true,
    availableDimensions: [
      // 1K
      { width: 1024, height: 1024, label: "1024×1024 (1:1) - 1K" },
      // 2K
      { width: 2048, height: 2048, label: "2048×2048 (1:1) - 2K" },
      { width: 2304, height: 1728, label: "2304×1728 (4:3) - 2K" },
      { width: 1728, height: 2304, label: "1728×2304 (3:4) - 2K" },
      { width: 2560, height: 1440, label: "2560×1440 (16:9) - 2K" },
      { width: 1440, height: 2560, label: "1440×2560 (9:16) - 2K" },
      { width: 2496, height: 1664, label: "2496×1664 (3:2) - 2K" },
      { width: 1664, height: 2496, label: "1664×2496 (2:3) - 2K" },
      { width: 3024, height: 1296, label: "3024×1296 (21:9) - 2K" },
      // 4K
      { width: 4096, height: 4096, label: "4096×4096 (1:1) - 4K" },
      { width: 4608, height: 3456, label: "4608×3456 (4:3) - 4K" },
      { width: 3456, height: 4608, label: "3456×4608 (3:4) - 4K" },
      { width: 5120, height: 2880, label: "5120×2880 (16:9) - 4K" },
      { width: 2880, height: 5120, label: "2880×5120 (9:16) - 4K" },
      { width: 4992, height: 3328, label: "4992×3328 (3:2) - 4K" },
      { width: 3328, height: 4992, label: "3328×4992 (2:3) - 4K" },
      { width: 6048, height: 2592, label: "6048×2592 (21:9) - 4K" },
    ],
  },
  {
    provider: "runware",
    endpointId: "google:4@1",
    label: "Gemini Flash Image 2.5",
    description: "Fast image generation from Google",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "google:1@1",
    label: "Imagen 3.0",
    description: "High-quality image generation from Google Imagen 3.0",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "google:1@2",
    label: "Imagen 3.0 Fast",
    description: "Fast variant of Google Imagen 3.0",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:108@20",
    label: "Qwen-Image-Edit",
    description: "Advanced image editing capabilities",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
    minSteps: 1,
    maxSteps: 100,
    defaultSteps: 28,
    minGuidanceScale: 0,
    maxGuidanceScale: 50,
    defaultGuidanceScale: 2.5,
    availableSchedulers: ["Default", "UniPC", "DDIM", "Euler", "DPM++"],
    defaultScheduler: "Default",
  },
  {
    provider: "runware",
    endpointId: "runware:108@21",
    label: "Qwen-Image-Edit Lightning (8 steps)",
    description: "Fast image editing with 8-step inference",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
    minSteps: 1,
    maxSteps: 100,
    defaultSteps: 8,
    minGuidanceScale: 0,
    maxGuidanceScale: 50,
    defaultGuidanceScale: 2.5,
  },
  {
    provider: "runware",
    endpointId: "runware:108@22",
    label: "Qwen-Image-Edit-Plus",
    description: "Enhanced image editing with advanced capabilities",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
    minGuidanceScale: 0,
    maxGuidanceScale: 50,
    defaultGuidanceScale: 4,
    availableSchedulers: ["FlowMatchEulerDiscreteScheduler", "Default"],
    defaultScheduler: "FlowMatchEulerDiscreteScheduler",
    availableAcceleration: ["none", "medium", "high"],
    defaultAcceleration: "medium",
    // NOTE: No steps parameter for this model - it uses acceleration instead
  },
  {
    provider: "runware",
    endpointId: "klingai:4@10",
    label: "Kolors 2.1",
    description: "Advanced color-aware image generation",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "klingai:5@10",
    label: "Kolors 2.0",
    description: "Color-focused image generation model",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:111@1",
    label: "FLUX.1 [dev] SRPO",
    description: "FLUX development model with SRPO optimization",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:108@1",
    label: "Qwen-Image",
    description: "Multimodal image generation from Qwen",
    popularity: 4,
    category: "image",
    hasNegativePrompt: true,
    minSteps: 1,
    maxSteps: 100,
    defaultSteps: 20,
    minGuidanceScale: 0,
    maxGuidanceScale: 50,
    defaultGuidanceScale: 2.5,
    availableDimensions: [
      { width: 1024, height: 1024, label: "1024×1024 (1:1) - Square" },
      { width: 1792, height: 768, label: "1792×768 (21:9) - Ultra-Wide" },
      { width: 1344, height: 768, label: "1344×768 (16:9) - Wide" },
      { width: 1024, height: 768, label: "1024×768 (4:3) - Standard" },
      { width: 1152, height: 768, label: "1152×768 (3:2) - Classic" },
      {
        width: 768,
        height: 1152,
        label: "768×1152 (2:3) - Classic Portrait",
      },
      {
        width: 768,
        height: 1024,
        label: "768×1024 (3:4) - Standard Portrait",
      },
      { width: 768, height: 1344, label: "768×1344 (9:16) - Tall" },
      { width: 768, height: 1792, label: "768×1792 (9:21) - Ultra-Tall" },
    ],
  },
  {
    provider: "runware",
    endpointId: "runware:108@5",
    label: "Qwen-Image-Lightning (4 steps)",
    description: "Ultra-fast image generation in 4 steps",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:108@6",
    label: "Qwen-Image-Lightning (8 steps V1.0)",
    description: "Fast image generation in 8 steps",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:108@7",
    label: "Qwen-Image-Lightning (8 steps V1.1)",
    description: "Improved 8-step image generation",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:107@1",
    label: "FLUX.1 Krea [dev]",
    description: "FLUX model optimized for creative workflows",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "bytedance:4@1",
    label: "SeedEdit 3.0",
    description: "Advanced image editing from ByteDance",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "bria:20@1",
    label: "Bria 2.0 Fast",
    description: "Fast image editing from Bria",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
    minSteps: 1,
    maxSteps: 50,
    defaultSteps: 50,
    minGuidanceScale: 1,
    maxGuidanceScale: 20,
    defaultGuidanceScale: 5,
    supportedAspectRatios: [
      { width: 1, height: 1, label: "1:1" },
      { width: 2, height: 3, label: "2:3" },
      { width: 3, height: 2, label: "3:2" },
      { width: 3, height: 4, label: "3:4" },
      { width: 4, height: 3, label: "4:3" },
      { width: 4, height: 5, label: "4:5" },
      { width: 5, height: 4, label: "5:4" },
      { width: 9, height: 16, label: "9:16" },
      { width: 16, height: 9, label: "16:9" },
    ],
  },
  {
    provider: "runware",
    endpointId: "bria:11@1",
    label: "Bria Image Replace Background",
    description: "Replace image backgrounds with AI-generated content",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "ideogram:1@1",
    label: "Ideogram 1.0",
    description: "Bold typography and clean illustrations",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "ideogram:1@2",
    label: "Ideogram 1.0 Remix",
    description: "Stylistic variations and remixing for Ideogram 1.0",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "ideogram:2@1",
    label: "Ideogram 2a",
    description: "Improved prompt following and image structure",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "ideogram:2@2",
    label: "Ideogram 2a Remix",
    description: "Expressive reinterpretation and themed variations",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "ideogram:3@1",
    label: "Ideogram 2.0",
    description: "Major improvements in rendering quality and text generation",
    popularity: 4,
    category: "image",
    hasNegativePrompt: true,
  },
  {
    provider: "runware",
    endpointId: "ideogram:3@2",
    label: "Ideogram 2.0 Remix",
    description: "Creative reinterpretations with new styles and moods",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
    hasNegativePrompt: true,
  },
  {
    provider: "runware",
    endpointId: "ideogram:3@3",
    label: "Ideogram 2.0 Edit",
    description: "Inpainting for precise image editing and text corrections",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
    hasNegativePrompt: true,
  },
  {
    provider: "runware",
    endpointId: "ideogram:3@4",
    label: "Ideogram 2.0 Reframe",
    description: "Outpainting to expand images with style consistency",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
    hasNegativePrompt: true,
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@1",
    label: "Ideogram 3.0",
    description: "Text-to-image with superior text rendering",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@2",
    label: "Ideogram 3.0 Remix",
    description: "Image remixing with style transfer",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@3",
    label: "Ideogram 3.0 Edit",
    description: "Precise image editing capabilities",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@4",
    label: "Ideogram 3.0 Reframe",
    description: "Image reframing and composition",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "ideogram:4@5",
    label: "Ideogram 3.0 Replace Background",
    description: "Background replacement for images",
    popularity: 4,
    category: "image",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "google:2@1",
    label: "Imagen 4 Preview",
    description: "Preview version of Google Imagen 4",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "google:2@2",
    label: "Imagen 4.0 Ultra",
    description: "Highest quality Imagen 4 model",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "google:2@3",
    label: "Imagen 4.0 Preview Fast",
    description: "Fast preview image generation from Google",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "openai:1@1",
    label: "GPT Image 1",
    description: "Image generation from OpenAI",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:106@1",
    label: "FLUX.1 Kontext [dev]",
    description: "FLUX development with context awareness",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
    availableDimensions: [
      { width: 1568, height: 672, label: "1568×672 (21:9)" },
      { width: 1392, height: 752, label: "1392×752 (16:9)" },
      { width: 1184, height: 880, label: "1184×880 (4:3)" },
      { width: 1248, height: 832, label: "1248×832 (3:2)" },
      { width: 1024, height: 1024, label: "1024×1024 (1:1)" },
      { width: 832, height: 1248, label: "832×1248 (2:3)" },
      { width: 880, height: 1184, label: "880×1184 (3:4)" },
      { width: 752, height: 1392, label: "752×1392 (9:16)" },
      { width: 672, height: 1568, label: "672×1568 (9:21)" },
    ],
  },
  {
    provider: "runware",
    endpointId: "bfl:3@1",
    label: "FLUX.1 Kontext [pro]",
    description: "Professional FLUX with context",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
    availableDimensions: [
      { width: 1568, height: 672, label: "1568×672 (21:9)" },
      { width: 1392, height: 752, label: "1392×752 (16:9)" },
      { width: 1184, height: 880, label: "1184×880 (4:3)" },
      { width: 1248, height: 832, label: "1248×832 (3:2)" },
      { width: 1024, height: 1024, label: "1024×1024 (1:1)" },
      { width: 832, height: 1248, label: "832×1248 (2:3)" },
      { width: 880, height: 1184, label: "880×1184 (3:4)" },
      { width: 752, height: 1392, label: "752×1392 (9:16)" },
      { width: 672, height: 1568, label: "672×1568 (9:21)" },
    ],
  },
  {
    provider: "runware",
    endpointId: "bfl:4@1",
    label: "FLUX.1 Kontext [max]",
    description: "Maximum quality FLUX with context",
    popularity: 5,
    category: "image",
    inputAsset: ["image"],
    availableDimensions: [
      { width: 1568, height: 672, label: "1568×672 (21:9)" },
      { width: 1392, height: 752, label: "1392×752 (16:9)" },
      { width: 1184, height: 880, label: "1184×880 (4:3)" },
      { width: 1248, height: 832, label: "1248×832 (3:2)" },
      { width: 1024, height: 1024, label: "1024×1024 (1:1)" },
      { width: 832, height: 1248, label: "832×1248 (2:3)" },
      { width: 880, height: 1184, label: "880×1184 (3:4)" },
      { width: 752, height: 1392, label: "752×1392 (9:16)" },
      { width: 672, height: 1568, label: "672×1568 (9:21)" },
    ],
  },
  {
    provider: "runware",
    endpointId: "bfl:2@1",
    label: "FLUX.1.1 [pro]",
    description: "Professional FLUX version 1.1",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "bfl:2@2",
    label: "FLUX.1.1 [pro] Ultra",
    description: "Ultra high-quality FLUX 1.1 Pro",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:97@1",
    label: "HiDream-I1 v1",
    description: "High-quality dream-like image generation v1",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:97@2",
    label: "HiDream-I1 v2",
    description: "High-quality dream-like image generation v2",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "runware:97@3",
    label: "HiDream-I1 v3",
    description: "High-quality dream-like image generation v3",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "rundiffusion:130@100",
    label: "Juggernaut Pro Flux by RunDiffusion",
    description: "Professional quality Flux model",
    popularity: 4,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "rundiffusion:110@101",
    label: "Juggernaut Lightning Flux by RunDiffusion",
    description: "Ultra-fast Flux generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:133005@782002",
    label: "Juggernaut XL",
    description: "Versatile realistic image generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:4201@130072",
    label: "Realistic Vision",
    description: "Photorealistic image generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:25694@143906",
    label: "DreamShaper",
    description: "Creative and artistic generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:7240@119057",
    label: "MeinaMix",
    description: "Anime-style image generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "civitai:81458@132760",
    label: "Epic Realism",
    description: "Ultra-realistic image generation",
    popularity: 5,
    category: "image",
  },
  {
    provider: "runware",
    endpointId: "sourceful:1@0",
    label: "Riverflow 1 Mini",
    description: "Fast and cost-efficient image editing model",
    popularity: 3,
    category: "image",
    inputAsset: ["image"],
    availableDimensions: [
      { width: 1024, height: 1024, label: "1024×1024 (1:1)" },
      { width: 1152, height: 864, label: "1152×864 (4:3)" },
      { width: 864, height: 1152, label: "864×1152 (3:4)" },
      { width: 1280, height: 720, label: "1280×720 (16:9)" },
      { width: 720, height: 1280, label: "720×1280 (9:16)" },
      { width: 1248, height: 832, label: "1248×832 (3:2)" },
      { width: 832, height: 1248, label: "832×1248 (2:3)" },
      { width: 1512, height: 648, label: "1512×648 (21:9)" },
      { width: 648, height: 1512, label: "648×1512 (9:21)" },
      { width: 1152, height: 896, label: "1152×896 (5:4)" },
      { width: 896, height: 1152, label: "896×1152 (4:5)" },
    ],
  },
  {
    provider: "runware",
    endpointId: "sourceful:1@1",
    label: "Riverflow 1",
    description:
      "Versatile daily image editing model supporting up to 10 input images",
    popularity: 3,
    category: "image",
    inputAsset: ["image"],
    availableDimensions: [
      { width: 1024, height: 1024, label: "1024×1024 (1:1)" },
      { width: 1152, height: 864, label: "1152×864 (4:3)" },
      { width: 864, height: 1152, label: "864×1152 (3:4)" },
      { width: 1280, height: 720, label: "1280×720 (16:9)" },
      { width: 720, height: 1280, label: "720×1280 (9:16)" },
      { width: 1248, height: 832, label: "1248×832 (3:2)" },
      { width: 832, height: 1248, label: "832×1248 (2:3)" },
      { width: 1512, height: 648, label: "1512×648 (21:9)" },
      { width: 648, height: 1512, label: "648×1512 (9:21)" },
      { width: 1152, height: 896, label: "1152×896 (5:4)" },
      { width: 896, height: 1152, label: "896×1152 (4:5)" },
    ],
  },
  {
    provider: "runware",
    endpointId: "sourceful:1@2",
    label: "Riverflow 1 Pro",
    description:
      "Advanced image editing model with superior quality and accuracy",
    popularity: 3,
    category: "image",
    inputAsset: ["image"],
    availableDimensions: [
      { width: 1024, height: 1024, label: "1024×1024 (1:1)" },
      { width: 1152, height: 864, label: "1152×864 (4:3)" },
      { width: 864, height: 1152, label: "864×1152 (3:4)" },
      { width: 1280, height: 720, label: "1280×720 (16:9)" },
      { width: 720, height: 1280, label: "720×1280 (9:16)" },
      { width: 1248, height: 832, label: "1248×832 (3:2)" },
      { width: 832, height: 1248, label: "832×1248 (2:3)" },
      { width: 1512, height: 648, label: "1512×648 (21:9)" },
      { width: 648, height: 1512, label: "648×1512 (9:21)" },
      { width: 1152, height: 896, label: "1152×896 (5:4)" },
      { width: 896, height: 1152, label: "896×1152 (4:5)" },
    ],
  },

  // ByteDance Video Models
  {
    provider: "runware",
    endpointId: "bytedance:2@2",
    label: "Seedance 1.0 Pro Fast",
    description:
      "Fast variant of Seedance 1.0 Pro for high-speed video generation. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    availableDurations: [5, 10],
    availableDimensions: [
      { width: 864, height: 480, label: "16:9 (480p)" },
      { width: 736, height: 544, label: "~4:3" },
      { width: 640, height: 640, label: "1:1 (Square)" },
      { width: 544, height: 736, label: "~3:4" },
      { width: 480, height: 864, label: "9:16 (480p)" },
      { width: 1920, height: 1088, label: "16:9 (1080p)" },
      { width: 1664, height: 1248, label: "4:3" },
      { width: 1440, height: 1440, label: "1:1 (Square HD)" },
      { width: 1248, height: 1664, label: "3:4" },
      { width: 1088, height: 1920, label: "9:16 (1080p)" },
      { width: 928, height: 2176, label: "~9:21 (Ultrawide Portrait)" },
      { width: 2176, height: 928, label: "~21:9 (Ultrawide)" },
    ],
    availableFps: [24],
    defaultDuration: 5,
    defaultWidth: 1920,
    defaultHeight: 1088,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "bytedance:2@1",
    label: "Seedance 1.0 Pro",
    description:
      "High-quality video generation with advanced features. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    availableDurations: [5, 10],
    availableDimensions: [
      { width: 864, height: 480, label: "16:9 (480p)" },
      { width: 736, height: 544, label: "~4:3" },
      { width: 640, height: 640, label: "1:1 (Square)" },
      { width: 544, height: 736, label: "~3:4" },
      { width: 480, height: 864, label: "9:16 (480p)" },
      { width: 1920, height: 1088, label: "16:9 (1080p)" },
      { width: 1664, height: 1248, label: "4:3" },
      { width: 1440, height: 1440, label: "1:1 (Square HD)" },
      { width: 1248, height: 1664, label: "3:4" },
      { width: 1088, height: 1920, label: "9:16 (1080p)" },
      { width: 928, height: 2176, label: "~9:21 (Ultrawide Portrait)" },
      { width: 2176, height: 928, label: "~21:9 (Ultrawide)" },
    ],
    availableFps: [24],
    defaultDuration: 5,
    defaultWidth: 1920,
    defaultHeight: 1088,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "bytedance:1@1",
    label: "Seedance 1.0 Lite",
    description:
      "Lightweight video generation model. Supports text-to-video and image-to-video",
    popularity: 4,
    category: "video",
    availableDurations: [5, 10],
    availableDimensions: [
      { width: 864, height: 480, label: "16:9 (480p)" },
      { width: 736, height: 544, label: "~4:3" },
      { width: 640, height: 640, label: "1:1 (Square)" },
      { width: 960, height: 416, label: "~21:9 (Ultrawide)" },
      { width: 416, height: 960, label: "~9:21 (Ultrawide Portrait)" },
      { width: 1248, height: 704, label: "16:9 (HD)" },
      { width: 1120, height: 832, label: "~4:3" },
      { width: 960, height: 960, label: "1:1 (Square HD)" },
      { width: 1504, height: 640, label: "~21:9 (Ultrawide HD)" },
      { width: 640, height: 1504, label: "~9:21 (Ultrawide Portrait HD)" },
    ],
    availableFps: [24],
    defaultDuration: 5,
    defaultWidth: 864,
    defaultHeight: 480,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "bytedance:5@1",
    label: "OmniHuman-1",
    description: "Human animation from image and audio",
    popularity: 4,
    category: "video",
    inputAsset: ["image", "audio"],
  },

  // Lightricks Video Models
  {
    provider: "runware",
    endpointId: "lightricks:2@0",
    label: "LTX-2 Pro",
    description:
      "Professional cinematic video generation with realistic motion and precise lighting control. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
    availableDurations: [6, 8, 10],
    availableDimensions: [
      {
        width: 1920,
        height: 1080,
        label: "16:9 (Standard / Landscape) - 1080p",
      },
      {
        width: 2560,
        height: 1440,
        label: "16:9 (Standard / Landscape) - 1440p",
      },
      { width: 3840, height: 2160, label: "16:9 (Standard / Landscape) - 4K" },
    ],
    availableFps: [25, 50],
    defaultDuration: 6,
    defaultWidth: 1920,
    defaultHeight: 1080,
    defaultFps: 25,
  },
  {
    provider: "runware",
    endpointId: "lightricks:2@1",
    label: "LTX-2 Fast",
    description:
      "High-speed cinematic video generation with efficient motion rendering. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
    availableDurations: [6, 8, 10],
    availableDimensions: [
      {
        width: 1920,
        height: 1080,
        label: "16:9 (Standard / Landscape) - 1080p",
      },
      {
        width: 2560,
        height: 1440,
        label: "16:9 (Standard / Landscape) - 1440p",
      },
      { width: 3840, height: 2160, label: "16:9 (Standard / Landscape) - 4K" },
    ],
    availableFps: [25, 50],
    defaultDuration: 6,
    defaultWidth: 1920,
    defaultHeight: 1080,
    defaultFps: 25,
  },

  // KlingAI Video Models
  {
    provider: "runware",
    endpointId: "klingai:6@0",
    label: "KlingAI 2.5 Turbo Standard",
    description: "Image-to-video with KlingAI 2.5 Turbo Standard",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "klingai:6@1",
    label: "KlingAI 2.5 Turbo Pro",
    description: "Text-to-video and image-to-video with KlingAI 2.5 Turbo Pro",
    popularity: 5,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
  },
  {
    provider: "runware",
    endpointId: "klingai:5@3",
    label: "KlingAI 2.1 Master",
    description:
      "Master quality video generation. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
  },
  {
    provider: "runware",
    endpointId: "klingai:5@2",
    label: "KlingAI 2.1 Pro",
    description: "Pro quality image-to-video generation",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "klingai:5@1",
    label: "KlingAI 2.1 Standard",
    description: "Standard quality image-to-video generation",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "klingai:4@3",
    label: "KlingAI 2.0 Master",
    description:
      "Master quality video generation. Supports text-to-video and image-to-video",
    popularity: 4,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
  },
  {
    provider: "runware",
    endpointId: "klingai:3@2",
    label: "KlingAI 1.6 Pro",
    description: "Pro quality image-to-video generation",
    popularity: 4,
    category: "video",
    inputAsset: ["image"],
  },
  {
    provider: "runware",
    endpointId: "klingai:3@1",
    label: "KlingAI 1.6 Standard",
    description:
      "Standard quality video generation. Supports text-to-video and image-to-video",
    popularity: 4,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
  },

  // MiniMax Video Models
  {
    provider: "runware",
    endpointId: "minimax:4@1",
    label: "MiniMax Hailuo 2.3",
    description:
      "Latest MiniMax Hailuo video generation model. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // From user's interface description
    availableDurations: [6, 10],
    availableDimensions: [
      { width: 1366, height: 768, label: "4:3 (Standard / Landscape) - 768p" },
      {
        width: 1920,
        height: 1080,
        label: "16:9 (Standard / Landscape) - 1080p",
      },
    ],
    availableFps: [24],
    defaultDuration: 6,
    defaultWidth: 1366,
    defaultHeight: 768,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "minimax:4@2",
    label: "MiniMax Hailuo 2.3 Fast",
    description:
      "Fast variant of MiniMax Hailuo 2.3 for high-speed generation. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // Same as Hailuo 2.3
    availableDurations: [6, 10],
    availableDimensions: [
      { width: 1366, height: 768, label: "4:3 (Standard / Landscape) - 768p" },
      {
        width: 1920,
        height: 1080,
        label: "16:9 (Standard / Landscape) - 1080p",
      },
    ],
    availableFps: [24],
    defaultDuration: 6,
    defaultWidth: 1366,
    defaultHeight: 768,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "minimax:3@1",
    label: "MiniMax 02 Hailuo",
    description: "MiniMax Hailuo 02 text-to-video model",
    popularity: 5,
    category: "video",
    availableDurations: [6, 10],
    availableDimensions: [
      { width: 1366, height: 768, label: "16:9 (768p)" },
      { width: 1920, height: 1080, label: "16:9 (1080p)" },
    ],
    availableFps: [25],
    defaultDuration: 6,
    defaultWidth: 1366,
    defaultHeight: 768,
    defaultFps: 25,
  },
  {
    provider: "runware",
    endpointId: "minimax:2@1",
    label: "MiniMax 01 Director",
    description:
      "MiniMax Hailuo 01 Director. Supports text-to-video and image-to-video",
    popularity: 4,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
    availableDurations: [6],
    availableDimensions: [{ width: 1366, height: 768, label: "16:9 (768p)" }],
    availableFps: [25],
    defaultDuration: 6,
    defaultWidth: 1366,
    defaultHeight: 768,
    defaultFps: 25,
  },

  // Vidu Video Models
  {
    provider: "runware",
    endpointId: "vidu:3@2",
    label: "Vidu Q2 Turbo",
    description: "High-speed Vidu Q2 video generation with reference support",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    availableDurations: [1, 2, 3, 4, 5, 6, 7, 8],
    availableDimensions: [
      { width: 640, height: 360, label: "16:9 - 360p" },
      { width: 960, height: 540, label: "16:9 - 540p" },
      { width: 1280, height: 720, label: "16:9 - 720p" },
      { width: 1920, height: 1080, label: "16:9 - 1080p" },
    ],
    availableFps: [24],
    defaultDuration: 5,
    defaultWidth: 1280,
    defaultHeight: 720,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "vidu:3@1",
    label: "Vidu Q2 Pro",
    description: "Professional Vidu Q2 video generation with enhanced quality",
    popularity: 5,
    category: "video",
    inputAsset: ["image"],
    availableDurations: [1, 2, 3, 4, 5, 6, 7, 8],
    availableDimensions: [
      { width: 640, height: 360, label: "16:9 - 360p" },
      { width: 960, height: 540, label: "16:9 - 540p" },
      { width: 1280, height: 720, label: "16:9 - 720p" },
      { width: 1920, height: 1080, label: "16:9 - 1080p" },
    ],
    availableFps: [24],
    defaultDuration: 5,
    defaultWidth: 1280,
    defaultHeight: 720,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "vidu:1@1",
    label: "Vidu Q1",
    description:
      "Vidu Q1 video generation. Supports text-to-video and image-to-video",
    popularity: 4,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
    availableDurations: [5],
    availableDimensions: [
      { width: 1920, height: 1080, label: "16:9 (1080p)" },
      { width: 1080, height: 1080, label: "1:1 (Square)" },
      { width: 1080, height: 1920, label: "9:16 (1080p Portrait)" },
    ],
    availableFps: [24],
    defaultDuration: 5,
    defaultWidth: 1920,
    defaultHeight: 1080,
    defaultFps: 24,
  },

  // Google Veo Video Models
  {
    provider: "runware",
    endpointId: "google:3@3",
    label: "Google Veo 3.1 Fast",
    description:
      "Optimized variant of Veo 3.1 for high-speed generation with cinematic quality. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // inputAsset removed - image is optional for text-to-video
    // Real constraints from user's screenshot (newer than docs)
    availableDurations: [4, 6, 8],
    availableDimensions: [
      { width: 1280, height: 720, label: "16:9 (Standard / Landscape) - 720p" },
      { width: 720, height: 1280, label: "9:16 (Standard / Portrait) - 720p" },
      {
        width: 1920,
        height: 1080,
        label: "16:9 (Standard / Landscape) - 1080p",
      },
      {
        width: 1080,
        height: 1920,
        label: "9:16 (Standard / Portrait) - 1080p",
      },
    ],
    availableFps: [24],
    defaultDuration: 4,
    defaultWidth: 1280,
    defaultHeight: 720,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "google:3@2",
    label: "Google Veo 3.1",
    description:
      "Google's newest Veo model for cinematic video generation with natural sound. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // inputAsset removed - image is optional for text-to-video
    availableDurations: [8],
    availableDimensions: [
      { width: 1280, height: 720, label: "16:9 (Standard / Landscape) - 720p" },
      { width: 720, height: 1280, label: "9:16 (Standard / Portrait) - 720p" },
      {
        width: 1920,
        height: 1080,
        label: "16:9 (Standard / Landscape) - 1080p",
      },
      {
        width: 1080,
        height: 1920,
        label: "9:16 (Standard / Portrait) - 1080p",
      },
    ],
    availableFps: [24],
    defaultDuration: 8,
    defaultWidth: 1280,
    defaultHeight: 720,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "google:3@1",
    label: "Google Veo 3 Fast",
    description:
      "Faster and more cost-effective variant of Veo 3, optimized for speed and affordability while maintaining native audio generation capabilities. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // inputAsset removed - image is optional for text-to-video
    availableDurations: [8],
    availableDimensions: [
      { width: 1280, height: 720, label: "16:9 (Standard / Landscape) - 720p" },
      { width: 720, height: 1280, label: "9:16 (Standard / Portrait) - 720p" },
      {
        width: 1920,
        height: 1080,
        label: "16:9 (Standard / Landscape) - 1080p",
      },
      {
        width: 1080,
        height: 1920,
        label: "9:16 (Standard / Portrait) - 1080p",
      },
    ],
    availableFps: [24],
    defaultDuration: 8,
    defaultWidth: 1280,
    defaultHeight: 720,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "google:3@0",
    label: "Google Veo 3",
    description:
      "Google Veo 3 video generation with text and image support. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // inputAsset removed - image is optional for text-to-video
    availableDurations: [8],
    availableDimensions: [
      { width: 1280, height: 720, label: "16:9 (Standard / Landscape) - 720p" },
      { width: 720, height: 1280, label: "9:16 (Standard / Portrait) - 720p" },
      {
        width: 1920,
        height: 1080,
        label: "16:9 (Standard / Landscape) - 1080p",
      },
      {
        width: 1080,
        height: 1920,
        label: "9:16 (Standard / Portrait) - 1080p",
      },
    ],
    availableFps: [24],
    defaultDuration: 8,
    defaultWidth: 1280,
    defaultHeight: 720,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "google:2@0",
    label: "Google Veo 2.0",
    description:
      "Google Veo 2.0 video generation model. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    availableDurations: [8],
    availableDimensions: [
      { width: 1280, height: 720, label: "16:9 (Standard / Landscape) - 720p" },
      { width: 720, height: 1280, label: "9:16 (Standard / Portrait) - 720p" },
      {
        width: 1920,
        height: 1080,
        label: "16:9 (Standard / Landscape) - 1080p",
      },
      {
        width: 1080,
        height: 1920,
        label: "9:16 (Standard / Portrait) - 1080p",
      },
    ],
    availableFps: [24],
    defaultDuration: 8,
    defaultWidth: 1280,
    defaultHeight: 720,
    defaultFps: 24,
  },

  // OpenAI Sora Video Models
  {
    provider: "runware",
    endpointId: "openai:3@2",
    label: "Sora 2 Pro",
    description:
      "OpenAI's Sora 2 Pro with enhanced quality and resolution. Supports text-to-video and image-to-video",
    cost: "~$0.5/video",
    popularity: 5,
    category: "video",
    // inputAsset removed - image is optional for text-to-video
    availableDurations: [4, 8, 12],
    availableDimensions: [
      { width: 1280, height: 720, label: "16:9 (Standard / Landscape) - 720p" },
      { width: 720, height: 1280, label: "9:16 (Standard / Portrait) - 720p" },
      { width: 1792, height: 1024, label: "7:4 (Wide)" },
      { width: 1024, height: 1792, label: "4:7 (Tall)" },
    ],
    availableFps: [24],
    defaultDuration: 8,
    defaultWidth: 1280,
    defaultHeight: 720,
    defaultFps: 24,
  },
  {
    provider: "runware",
    endpointId: "openai:3@1",
    label: "Sora 2",
    description:
      "OpenAI's Sora 2 video generation model. Supports text-to-video and image-to-video",
    cost: "$0.4/video",
    popularity: 5,
    category: "video",
    // inputAsset removed - image is optional for text-to-video
    availableDurations: [4, 8, 12],
    availableDimensions: [
      { width: 1280, height: 720, label: "16:9 (Standard / Landscape) - 720p" },
      { width: 720, height: 1280, label: "9:16 (Standard / Portrait) - 720p" },
    ],
    availableFps: [24, 30],
    defaultDuration: 4,
    defaultWidth: 1280,
    defaultHeight: 720,
    defaultFps: 30,
  },

  // PixVerse Video Models
  {
    provider: "runware",
    endpointId: "pixverse:1@5",
    label: "PixVerse v5",
    description:
      "Latest PixVerse video generation. Supports text-to-video and image-to-video",
    popularity: 5,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
    hasNegativePrompt: true,
    availableDurations: [5, 8],
    defaultDuration: 5,
    availableDimensions: [
      // 16:9 (Landscape)
      { width: 640, height: 360, label: "640×360 (16:9) - 360p" },
      { width: 960, height: 540, label: "960×540 (16:9) - 540p" },
      { width: 1280, height: 720, label: "1280×720 (16:9) - 720p" },
      { width: 1920, height: 1080, label: "1920×1080 (16:9) - 1080p" },
      // 4:3 (Standard)
      { width: 480, height: 360, label: "480×360 (4:3) - 360p" },
      { width: 720, height: 540, label: "720×540 (4:3) - 540p" },
      { width: 960, height: 720, label: "960×720 (4:3) - 720p" },
      { width: 1440, height: 1080, label: "1440×1080 (4:3) - 1080p" },
      // 1:1 (Square)
      { width: 360, height: 360, label: "360×360 (1:1) - 360p" },
      { width: 540, height: 540, label: "540×540 (1:1) - 540p" },
      { width: 720, height: 720, label: "720×720 (1:1) - 720p" },
      { width: 1080, height: 1080, label: "1080×1080 (1:1) - 1080p" },
      // 3:4 (Portrait)
      { width: 360, height: 480, label: "360×480 (3:4) - 360p" },
      { width: 540, height: 720, label: "540×720 (3:4) - 540p" },
      { width: 720, height: 960, label: "720×960 (3:4) - 720p" },
      { width: 1080, height: 1440, label: "1080×1440 (3:4) - 1080p" },
      // 9:16 (Tall)
      { width: 360, height: 640, label: "360×640 (9:16) - 360p" },
      { width: 540, height: 960, label: "540×960 (9:16) - 540p" },
      { width: 720, height: 1280, label: "720×1280 (9:16) - 720p" },
      { width: 1080, height: 1920, label: "1080×1920 (9:16) - 1080p" },
    ],
  },
  {
    provider: "runware",
    endpointId: "pixverse:1@3",
    label: "PixVerse v4.5",
    description:
      "PixVerse v4.5 video generation. Supports text-to-video and image-to-video",
    popularity: 4,
    category: "video",
    // inputAsset removed - supports both text-to-video and image-to-video
  },
  {
    provider: "runware",
    endpointId: "pixverse:lipsync@1",
    label: "PixVerse LipSync",
    description: "Lip sync for video avatars",
    popularity: 4,
    category: "video",
    inputAsset: ["video", "audio"],
  },

  // Runware Video Models
  {
    provider: "runware",
    endpointId: "runware:201@1",
    label: "Wan2.5-Preview",
    description: "Preview of Runware Wan 2.5 video model",
    popularity: 5,
    category: "video",
  },
  {
    provider: "runware",
    endpointId: "runware:200@8",
    label: "Wan2.2 A14B Turbo",
    description:
      "Turbo variant of Runware Wan 2.2 A14B for high-speed generation",
    popularity: 5,
    category: "video",
  },
  {
    provider: "runware",
    endpointId: "runware:200@6",
    label: "Wan2.2 A14B",
    description: "Runware Wan 2.2 A14B video generation model",
    popularity: 5,
    category: "video",
  },
  {
    provider: "runware",
    endpointId: "runware:190@1",
    label: "Ovi",
    description: "Runware Ovi video generation model",
    popularity: 5,
    category: "video",
  },

  {
    provider: "runware",
    endpointId: "elevenlabs:1@1",
    label: "ElevenLabs Music v1",
    description: "Music generation from ElevenLabs",
    popularity: 4,
    category: "music",
  },
];
